# arxiv/references-agent

FROM arxiv/base:0.6

WORKDIR /opt/arxiv

ADD Pipfile /opt/arxiv/
ADD Pipfile.lock /opt/arxiv/

ENV KINESIS_ENDPOINT ""
ENV KINESIS_VERIFY "true"
ENV KINESIS_SHARD_ID "shardId-000000000000"
ENV KINESIS_STREAM "PDFIsAvailable"
ENV KINESIS_CHECKPOINT_VOLUME /checkpoint

RUN pip install pipenv
RUN pipenv install

# Add the application itself last, for faster builds on minor revisions.
ADD references /opt/arxiv/references/
ADD bin/start_api.sh /opt/arxiv/
RUN chmod +x /opt/arxiv/start_api.sh

VOLUME /checkpoint

EXPOSE 8000

ENTRYPOINT ["/opt/arxiv/start_api.sh"]
CMD ["--http-socket", ":8000", \
     "-M", \
     "-t 3000", \
     "--manage-script-name", \
     "--processes", "8", \
     "--threads", "1", \
     "--async", "100", \
     "--ugreen", \
     "--mount", "/references=wsgi.py", \
     "--logformat", "%(addr) %(addr) - %(user_id)|%(session_id) [%(rtime)] [%(uagent)] \"%(method) %(uri) %(proto)\" %(status) %(size) %(micros) %(ttfb)"]
