# arxiv/references-agent

FROM arxiv/base:0.6

WORKDIR /opt/arxiv

ADD Pipfile /opt/arxiv/
ADD Pipfile.lock /opt/arxiv/

ENV KINESIS_ENDPOINT ""
ENV KINESIS_VERIFY "true"
ENV KINESIS_SHARD_ID "shardId-000000000000"
ENV KINESIS_STREAM "PDFIsAvailable"
ENV KINESIS_CHECKPOINT_VOLUME /checkpoint

RUN pip install pipenv
RUN pipenv install

# Add the application itself last, for faster builds on minor revisions.
ADD references /opt/arxiv/references/
ADD bin/start_agent.py /opt/arxiv/

VOLUME /checkpoint

CMD ["pipenv", "run", "python", "start_agent.py"]

ADD references /opt/arxiv/references/

ENTRYPOINT ["pipenv", "run", "celery", "worker"]
CMD ["-A", "references.worker.celery_app", "--loglevel=INFO", "-E", "--concurrency=4"]
