# arxiv/references-agent

FROM ubuntu:zesty

RUN apt-get update
RUN apt-get -y update
RUN apt-get install -y ca-certificates wget

# Install Python 3.6 and friends.
RUN apt-get install -y libpython3.6 python3.6 python3.6-dev python3.6-venv
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.6 get-pip.py

RUN apt-get install -y gcc g++

# Add Python consumer and configuration.
ADD requirements/worker.txt /opt/arxiv/requirements.txt
ADD wsgi.py /opt/arxiv/
RUN pip install -U pip
RUN pip install -r /opt/arxiv/requirements.txt

ENV PATH "/opt/arxiv:${PATH}"

# Runtime configuration.
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""
ENV REDIS_ENDPOINT ""

# If not set, secrets will not be retrieved.
ENV SECRETS_BUCKET_NAME ""
ENV ARXIV_HOME "https://arxiv.org"

ADD references /opt/arxiv/references/

WORKDIR /opt/arxiv
ENTRYPOINT ["celery", "worker"]
CMD ["-A", "references.celery", "--loglevel=DEBUG", "-E", "--concurrency=4"]
