# arxiv/references-worker

FROM ubuntu:zesty

RUN apt-get update && apt-get install -y \
    ca-certificates \
    wget \
    gcc \
    g++ \
    libpython3.6 \
    python3.6 \
    python3.6-dev \
    python3.6-venv \
 && rm -rf /var/lib/apt/lists/*

# Install Python 3.6 and friends.
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.6 get-pip.py

# Add Python consumer and configuration.
ADD requirements/worker.txt /opt/arxiv/requirements.txt
ADD wsgi.py /opt/arxiv/
RUN pip install -U pip
RUN pip install -r /opt/arxiv/requirements.txt

ENV PATH "/opt/arxiv:${PATH}"

# Runtime configuration.
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""
ENV REDIS_ENDPOINT ""

# If not set, secrets will not be retrieved.
ENV SECRETS_BUCKET_NAME ""
ENV ARXIV_HOME "https://arxiv.org"
ENV CREDENTIALS_ROLE "arxiv-references-worker"
ENV CREDENTIALS_URL "http://169.254.169.254/latest/meta-data/iam/security-credentials"

ADD references /opt/arxiv/references/

WORKDIR /opt/arxiv
ENTRYPOINT ["celery", "worker"]
CMD ["-A", "references.worker.celery_app", "--loglevel=DEBUG", "-E", "--concurrency=4"]
