# arxiv/references-api

FROM ubuntu:zesty

RUN apt-get update && apt-get install -y \
    ca-certificates \
    wget \
    gcc \
    g++ \
    libpython3.6 \
    python3.6 \
    python3.6-dev \
    python3.6-venv \
 && rm -rf /var/lib/apt/lists/*

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.6 get-pip.py

# Add Python consumer and configuration.
ADD requirements/web.txt /opt/arxiv/requirements.txt
RUN pip install -U pip && \
    pip install -r /opt/arxiv/requirements.txt && \
    pip install -U nose

ADD references /opt/arxiv/references/
ADD tests/e2e/ /opt/arxiv/tests/e2e/
ADD schema /opt/arxiv/schema/

ENV PATH "/opt/arxiv:${PATH}"

# Runtime configuration.
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""

ENV ARXIV_HOME "https://arxiv.org"
ENV REFEXTRACT_ENDPOINT ""


WORKDIR /opt/arxiv
CMD ["nosetests", "--verbosity=3", "tests/e2e/test_e2e.py"]
