# arxiv/references-agent

FROM ubuntu:zesty

RUN apt-get update
RUN apt-get -y update
RUN apt-get install -y ca-certificates wget

# Install Python 3.6 and friends.
RUN apt-get install -y libpython3.6 python3.6 python3.6-dev python3.6-venv
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.6 get-pip.py
#RUN ln -s /usr/bin/python3.6 /usr/local/bin/python3
#RUN ln -s /usr/local/bin/pip /usr/local/bin/pip3


# Add Python consumer and configuration.
ADD references /opt/arxiv/references/
ADD requirements.txt /opt/arxiv/
ADD wsgi.py /opt/arxiv/
ADD start_app.sh /opt/arxiv/
RUN pip install -U pip
RUN pip install -r /opt/arxiv/requirements.txt

RUN apt-get install -y gcc

ENV PATH "/opt/arxiv:${PATH}"

# Runtime configuration.
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""

# If not set, secrets will not be retrieved.
ENV SECRETS_BUCKET_NAME ""
ENV ARXIV_HOME "https://arxiv.org"

ENTRYPOINT ["celery", "worker"]
CMD ["-A reflink", "--loglevel=INFO", "-E", "--concurrency=4"]
