#!/bin/sh
#
# reflink-worker          Reflink Service Worker
#
# chkconfig: 2345 90 60
# description: Performs reference extraction and link injection.
#

case "$1" in
start)
   /sbin/runuser reflinkworker -s /bin/bash -c "/opt/reflink/bin/start_worker && echo $!>/var/run/reflinkworker.pid" &
   ;;
stop)
   kill `cat /var/run/reflinkworker.pid`
   rm /var/run/reflinkworker.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/reflinkworker.pid ]; then
      echo reflink worker is running, pid=`cat /var/run/reflinkworker.pid`
   else
      echo reflink worker is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
